name: Generate Terraform documentation

on:
  - pull_request

permissions:
  contents: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    name: terraform-docs-action
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render Terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"